global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ryu-controller'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'routers'
    static_configs:
      - targets: ['192.168.100.11:9100', '192.168.100.12:9100']

  - job_name: 'clients'
    static_configs:
      - targets: ['192.168.100.21:9100', '192.168.100.22:9100']
